### PR TITLE
add Date/Time setters

### PR DESCRIPTION
**Pull request by aplavin**

### CODE REVIEW

**Review by jw3126 — APPROVED** [review]
LGTM, this code is really beautiful @aplavin thanks a lot!

**Comment by jw3126** [comment]
Btw I would love to give you commit access to this repo. I remember you having some objections to 2FA though. Should these objections at some point be no longer relevant, please tell me and I am happy to invite you again.

**Comment by jw3126** [comment]
Can you bump the patch version?

**Comment by aplavin** [comment]
> Very nice, see also https://discourse.julialang.org/t/replace-date-year/68301?u=jw3126

Indeed, turns out I have a similar usecase.

> Btw I would love to give you commit access to this repo. 

I had to enable 2fa for other reasons in the meantime, so would be happy to be invited!

> Can you bump the patch version?

Done!

**Pull request merged**
